version: '3'
services:
  web:
    build: node
    image: "node-minimum"
    container_name: "node-minimum"
    tty: true
    volumes: 
      - ./node/app:/app
    ports:
      - "8080:8080" 
    command: sh -c 'chown -R 1000:1000 /app && sh'
